//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface ChatRoomPrx extends com.zeroc.Ice.ObjectPrx
{
    default void login(String nickname)
        throws ChatException
    {
        login(nickname, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void login(String nickname, java.util.Map<String, String> context)
        throws ChatException
    {
        try
        {
            _iceI_loginAsync(nickname, context, true).waitForResponseOrUserEx();
        }
        catch(ChatException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> loginAsync(String nickname)
    {
        return _iceI_loginAsync(nickname, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> loginAsync(String nickname, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(nickname, context, false);
    }

    /**
     * @hidden
     * @param iceP_nickname -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_loginAsync(String iceP_nickname, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "login", null, sync, _iceE_login);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nickname);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_login =
    {
        ChatException.class
    };

    default void postMessage(String nickname, String message)
        throws ChatException
    {
        postMessage(nickname, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void postMessage(String nickname, String message, java.util.Map<String, String> context)
        throws ChatException
    {
        try
        {
            _iceI_postMessageAsync(nickname, message, context, true).waitForResponseOrUserEx();
        }
        catch(ChatException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> postMessageAsync(String nickname, String message)
    {
        return _iceI_postMessageAsync(nickname, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> postMessageAsync(String nickname, String message, java.util.Map<String, String> context)
    {
        return _iceI_postMessageAsync(nickname, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_nickname -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_postMessageAsync(String iceP_nickname, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "postMessage", null, sync, _iceE_postMessage);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nickname);
                     ostr.writeString(iceP_message);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_postMessage =
    {
        ChatException.class
    };

    default ChatMessage[] getPendingMessages(String nickname, long lastMessageId)
    {
        return getPendingMessages(nickname, lastMessageId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ChatMessage[] getPendingMessages(String nickname, long lastMessageId, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(nickname, lastMessageId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ChatMessage[]> getPendingMessagesAsync(String nickname, long lastMessageId)
    {
        return _iceI_getPendingMessagesAsync(nickname, lastMessageId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ChatMessage[]> getPendingMessagesAsync(String nickname, long lastMessageId, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(nickname, lastMessageId, context, false);
    }

    /**
     * @hidden
     * @param iceP_nickname -
     * @param iceP_lastMessageId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ChatMessage[]> _iceI_getPendingMessagesAsync(String iceP_nickname, long iceP_lastMessageId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ChatMessage[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPendingMessages", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nickname);
                     ostr.writeLong(iceP_lastMessageId);
                 }, istr -> {
                     ChatMessage[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String[] getOnlineUsers()
    {
        return getOnlineUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getOnlineUsers(java.util.Map<String, String> context)
    {
        return _iceI_getOnlineUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync()
    {
        return _iceI_getOnlineUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getOnlineUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getOnlineUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getOnlineUsers", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default void logout(String nickname)
    {
        logout(nickname, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void logout(String nickname, java.util.Map<String, String> context)
    {
        _iceI_logoutAsync(nickname, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> logoutAsync(String nickname)
    {
        return _iceI_logoutAsync(nickname, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> logoutAsync(String nickname, java.util.Map<String, String> context)
    {
        return _iceI_logoutAsync(nickname, context, false);
    }

    /**
     * @hidden
     * @param iceP_nickname -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_logoutAsync(String iceP_nickname, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "logout", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_nickname);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatRoomPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatRoomPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatRoomPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatRoomPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatRoomPrx ice_adapterId(String newAdapterId)
    {
        return (ChatRoomPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatRoomPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatRoomPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatRoomPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatRoomPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in milliseconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatRoomPrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatRoomPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatRoomPrx ice_connectionCached(boolean newCache)
    {
        return (ChatRoomPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatRoomPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatRoomPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatRoomPrx ice_secure(boolean b)
    {
        return (ChatRoomPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatRoomPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatRoomPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatRoomPrx ice_preferSecure(boolean b)
    {
        return (ChatRoomPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatRoomPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatRoomPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatRoomPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatRoomPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatRoomPrx ice_collocationOptimized(boolean b)
    {
        return (ChatRoomPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatRoomPrx ice_twoway()
    {
        return (ChatRoomPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatRoomPrx ice_oneway()
    {
        return (ChatRoomPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatRoomPrx ice_batchOneway()
    {
        return (ChatRoomPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatRoomPrx ice_datagram()
    {
        return (ChatRoomPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatRoomPrx ice_batchDatagram()
    {
        return (ChatRoomPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatRoomPrx ice_compress(boolean co)
    {
        return (ChatRoomPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatRoomPrx ice_timeout(int t)
    {
        return (ChatRoomPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatRoomPrx ice_connectionId(String connectionId)
    {
        return (ChatRoomPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatRoomPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatRoomPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ChatApp::ChatRoom";
    }
}
