//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public class ChatMessage implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public long id;

    public String sender;

    public String text;

    public String timestamp;

    public ChatMessage()
    {
        this.sender = "";
        this.text = "";
        this.timestamp = "";
    }

    public ChatMessage(long id, String sender, String text, String timestamp)
    {
        this.id = id;
        this.sender = sender;
        this.text = text;
        this.timestamp = timestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ChatMessage r = null;
        if(rhs instanceof ChatMessage)
        {
            r = (ChatMessage)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.text != r.text)
            {
                if(this.text == null || r.text == null || !this.text.equals(r.text))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ChatApp::ChatMessage");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, text);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        return h_;
    }

    public ChatMessage clone()
    {
        ChatMessage c = null;
        try
        {
            c = (ChatMessage)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.id);
        ostr.writeString(this.sender);
        ostr.writeString(this.text);
        ostr.writeString(this.timestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readLong();
        this.sender = istr.readString();
        this.text = istr.readString();
        this.timestamp = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ChatMessage v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ChatMessage ice_read(com.zeroc.Ice.InputStream istr)
    {
        ChatMessage v = new ChatMessage();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ChatMessage> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ChatMessage v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ChatMessage> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ChatMessage.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ChatMessage _nullMarshalValue = new ChatMessage();

    /** @hidden */
    public static final long serialVersionUID = -541800608530790476L;
}
